SELECT d.CON_ID, '<div nowrap align="left"><font color="#336699"><b>' || owner ||'</b></font></div>' owner,
       object_name TRIGGER_NAME,
       D.OBJECT_TYPE,
       D.CREATED,
  d.status,
       (SELECT nb.status
          FROM cdb_triggers nb
         WHERE nb.owner = d.owner
           AND  nb.trigger_name = d.OBJECT_NAME
					 and nb.CON_ID=d.CON_ID)  STATUS1
  FROM cdb_objects D
 WHERE owner NOT IN ('SYS','SYSTEM','PUBLIC','MDSYS','TSMSYS','DMSYS','DBSNMP','SCOTT','LHR','LHR2','DB_MONITOR','OUTLN','MGMT_VIEW','FLOWS_FILES','ORDSYS','EXFSYS','WMSYS','APPQOSSYS','APEX_030200','APEX_050000','OWBSYS_AUDIT','ORDDATA','CTXSYS','ANONYMOUS','SYSMAN','XDB','ORDPLUGINS','OWBSYS','SI_INFORMTN_SCHEMA','OLAPSYS','ORACLE_OCM','XS$NULL','BI','PM','MDDATA','IX','SH','DIP','OE','APEX_PUBLIC_USER','HR','SPATIAL_CSW_ADMIN_USR','SPATIAL_WFS_ADMIN_USR','APEX_040200','DVSYS','LBACSYS','GSMADMIN_INTERNAL','AUDSYS','OJVMSYS','SYS$UMF','GGSYS','DBSFWUSER','DVF','GSMCATUSER','SYSBACKUP','REMOTE_SCHEDULER_AGENT','GSMUSER','SYSRAC','SYSKM','SYSDG','PDBADMIN','WKSYS','GSMROOTUSER','CSMIG','WKPROXY','WK_TEST','SI_INFORMATN_SCHEMA')
   AND  status <> 'VALID'
   AND  D.OBJECT_TYPE='TRIGGER'
 ORDER BY d.CON_ID, owner, object_name;
